### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by in4matix** [neuromorph/utils#1]
Hey,
I don't know how else to contact you. I have forked a repo, but only recently started learning code, and have not been able to get anywhere after trying, so I was wondering if you would be interested at taking on this project to make it work on Gnome 42 as your coding skills seem to be top notch.
Here is the link to the original repo: https://github.com/Selenium-H/Notification-Center
I don't mind if you take over this project and release it. It really seems like a cool extension, and even although I got more or less the same result using Big Sur Status Area, this extension is very buggy.

**Comment by neuromorph** [comment]
Hello,

I had a look at it. They have ported it to Gnome 42 in the Experimental branch. I was able to install it. 
You can download the zip from their Github (Experimental branch) - https://github.com/Selenium-H/Notification-Center/archive/refs/heads/Experimental.zip
Download and unzip it and open terminal in that folder. Then follow manual install instructions on ReadMe (basically run install.sh script). 
For me, after install it wasn't working initially, until I clicked on the "Reset Notification Center" button at top of the Preferences window.

Good luck!

**Comment by in4matix** [comment]
Hi.
Thank you so much for figuring this out. It is really such an awesome extension, and really sad that it has been abandoned. It really seems to be working well. Only issue so far is that it cannot display the notification (bell) icon. Not sure at all why. The code is all Greek to me at this stage. Perhaps I am not cut out to be a coder...
![n_icon](https://github.com/neuromorph/utils/assets/62904593/709d632b-5678-4945-b4b0-afef317b8ac9)

**Comment by neuromorph** [comment]
Well, it seems to work for me. I got an icon but it was something like a message icon. When I enabled this setting in the preferences, I got a bell icon:-  'Change icon depending if there is a notification or not'.
I am attaching the zip of what I have installed, you can try with this.

[notification-center@Selenium-H.zip](https://github.com/neuromorph/utils/files/14473700/notification-center%40Selenium-H.zip)

**Comment by neuromorph** [comment]
OK, an update. I was messing with my user themes for some reason and once I faced the same red box as you. I looked in the code and they are using many icons to show different notifications e.g. for calendar, media, whether notification disabled or enabled etc. You can search in their `extension.js` for 'symbolic' to see the icon names. Your icon theme should have those icons else it will show an error placeholder.

**Comment by in4matix** [comment]
I'm so glad you found a solution!! You might as well fork this extension and take it over ;-) (If you want to)

**Comment by in4matix** [comment]
After playing around a bit more, I discovered that disabling one setting makes the panel icon work on the stock Ubuntu Yaru theme.
![Screenshot from 2024-03-04 07-59-05](https://github.com/neuromorph/utils/assets/62904593/a215d97a-6b87-4ff4-919d-ee1a7c46e7ce)
![Screenshot from 2024-03-04 08-01-12](https://github.com/neuromorph/utils/assets/62904593/7b4c6ff9-80e9-40f4-a490-b3c96f188f17)

**Comment by neuromorph** [comment]
Cool! Glad it worked for you!
No plan to take over the extension :) Hope they update it, you can leave an issue on their repo in case they or someone else decides to update it.
